version: '3'

services:
  db:
    image: postgres
    volumes:
        - ../.././db/psql:/var/lib/postgresql/data:rw
  api:
    build: ../../.
    # command: python3 manage.py runserver 0.0.0.0:8000
    command: bash -c "chmod +x provision/prod/run.sh && ./provision/prod/run.sh"
    volumes:
      - ../../.:/code
      - /static:/static
    expose:
      - "8000"
    depends_on:
      - db
  nginx:
    image: nginx
    ports:
      - "80:8000"
    volumes:
      - ../../.:/code
      - ../.././nginx:/etc/nginx/conf.d
      - /static:/static
    depends_on:
      - api
