version: '3'

services:
  db:
    image: postgres
    volumes:
        - ../../../data:/var/lib/postgresql/data:rw
        - ../scripts/db:/docker-entrypoint-initdb.d:rw
  api:
    build: ../../.
    command: bash -c "chmod +x provision/scripts/run.sh && ./provision/scripts/run.sh"
    volumes:
      - ../../.:/code
      - /static:/static
    expose:
      - "8000"
    depends_on:
      - db
  nginx:
    image: nginx
    ports:
      - "80:8000"
    volumes:
      - ../../.:/code
      - ../.././nginx:/etc/nginx/conf.d
      - /static:/static
    depends_on:
      - api
