---
- hosts: mediga_dev
  vars_files:
    - vars.yml
  gather_facts: false
  become: yes

  tasks:
    - name: Install system packages
      apt:
        pkg: "{{ item }}"
        update-cache: yes
      with_items: "{{ system_packages }}"

    - name: Create directory for app
      file:
        path: "{{ install_root }}/{{ project_name }}"
        state: directory

    - name: Check if PostgreSQL is running
      service:
        name: postgresql
        state: started

    - name: Create project database
      become_user: postgres
      postgresql_db:
        name: "{{ db_name }}"
        encoding: UTF-8

    - name: Create project database user
      become_user: postgres
      postgresql_user:
        db: "{{ db_name }}"
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: ALL

    - name: Remove nginx default site
      file:
        path: "/etc/nginx/sites-enabled/default"
        state: absent

- import_playbook: deploy.yml
